"""Initial alembic

Revision ID: bb0cccea3ff9
Revises:
Create Date: 2024-06-26 23:37:54.324917

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bb0cccea3ff9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_series_title"), "series", ["title"], unique=False)
    op.create_table(
        "movies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_title"), "movies", ["title"], unique=False)
    op.create_table(
        "serie_seasons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("serie_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["serie_id"], ["series.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "serie_episodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column("serie_season_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"]),
        sa.ForeignKeyConstraint(["serie_season_id"], ["serie_seasons.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("serie_episodes")
    op.drop_table("serie_seasons")
    op.drop_index(op.f("ix_movies_title"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_series_title"), table_name="series")
    op.drop_table("series")
    op.drop_table("media")
    # ### end Alembic commands ###
